language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm test -- --coverage
  - npm run build
after_script:
  - npm run coveralls
notifications:
  webhooks: https://coveralls.io/webhook