  name: Unassigned Issues Are To Do

  on:
    issues:
      types: [unassigned]

  jobs:
    move-to-to-do:
      runs-on: ubuntu-latest
      name: Move to To Do Column
      steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Move to To Do
        uses: kin/gh-action-move-issues-to-column@v1.0
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          project-name: "Roadmap"
          target-column: "To do"